name: Test, Build and Deploy

on:
  pull_request:
    types: [closed]

jobs:
  build-test-release:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test:ci

      - name: Raise version of affected libraries
        run: |
          LATEST_TAG=$(git tag -l "v*" --sort=-version:refname | head -n 1)
          LIBS=$(yarn nx affected:libs --base=$LATEST_TAG --head=HEAD --plain | awk 'NR > 2 && $1 != "Done" { print $1 }')
          for LIBRARY in $LIBS
          do
            cd ./libs/$LIBRARY
            npm version minor --no-git-tag-version --no-push
            echo "Bumping $LIBRARY"
            cd ..
            cd ..
          done
          npm version minor --no-git-tag-version --no-push

      - name: Build components
        run: yarn nx affected:build --prod --with-deps --base=main

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Push changes
        run: |
          git fetch
          git config user.email "unicorn.ci@yonatankra.com"
          git config user.name "Unicorn CI"
          git add --all
          git commit -m "update versions to ${{ steps.package-version.outputs.current-version }}"
          git push

      - name: Tag release
        run: |
          git tag -a v${{ steps.package-version.outputs.current-version }} -m "tag release v${{ steps.package-version.outputs.current-version }}"
          git push --follow-tags

      - name: Build Demo
        run: yarn build:deploy

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/apps/unicorn-hunt # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
